services:
  postgres:
    container_name: webhooks-api-db
    image: postgres:17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webhooks
    ports:
      - '5432:5432'
